TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
# Create and install (or just install) into <top>/db
DB += rga.db


include $(TOP)/configure/RULES
#----------------------------------------
