TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
# Create and install (or just install) into <top>/db
DB += tpg.db


include $(TOP)/configure/RULES
#----------------------------------------
